Feature
ichsansandy/capstone-htmlcssjs pull request #1
Opened 2023-05-21 13:43 UTC by ichsansandy

# Capstone Project
- Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).
- Design for Home and About page
- Desktop Version and Mobile Version
- Talent Section render using JavaScript

2023-05-22 06:36 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @ichsansandy 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that doesn't have a proper branch name & PR title. The branch should have a name of a feature or action and the Pull Request should have a descriptive title telling the reviewer what changes are inside. Please make sure those two are always intact before you request a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-22 08:07 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @ichsansandy 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Amazing UI & UX 👏 ✔
-  Well-structured files ✔
-  Tailored & unique content ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-22 08:07 UTC, AbelG101 commented on README.md
> +
- [ ] Kindly make sure you attach a link to the deployed project in the "Live Demo" section here, instead of a link to google.com 😅
- [ ] Also, please record a video presenting the project's features and add a link to the video either on the readme file or the PR description. The maximum length of the video should be 5 minutes.

2023-05-22 08:07 UTC, AbelG101 commented on app.js
> +              <img class="talent-image" src="${talent.img}" alt="" />
- [ ] Please make sure to add an appropriate text to the `alt` attribute here as they will help assistive devices like screen readers to describe what the images are about for people with disabilities. ✔

2023-05-22 08:14 UTC, ichsansandy commented on README.md
> +
Hi @AbelG101
Thanks for the constructive feedback
is the video really required or it's optional?

2023-05-22 08:23 UTC, AbelG101 commented on README.md
> +
Hey @ichsansandy, It's required.

2023-05-22 08:25 UTC, ichsansandy commented on README.md
> +
Alright thanks

2023-05-22 09:39 UTC, gemmen29 approved these changes
Hi @ichsansandy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-22 09:41 UTC, merged

2023-07-31 08:30 UTC, shella12 reviewed
Hi @ichsansandy, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a wring project link, expected a react project and instead got HTML/Js capstone project. Please resubmit the project with correct repo link

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._